import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * This class allows the user to create new airports for the system.
 * It will tell the director when a new airport is created, and in turn
 * the director will add the airport to the system. 
 */

@SuppressWarnings("serial")
public class addAirport extends javax.swing.JDialog {

	/**
	 * Creates new form addAirport
	 */
	Director d;



	public addAirport(Director d) {
		this.d=d;
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	
	//NETBEANS was used to build GUI. All actionlisteners were built to suit our needs
	private void initComponents() {

		code = new javax.swing.JLabel();
		airCodeField = new javax.swing.JTextField();
		addButton = new javax.swing.JToggleButton();
		result = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Add a New Airport");

		code.setText("Airport Code");

		addButton.setText("Add");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt,airCodeField,result);
			}
		});//change


		result.setText("                                 ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(38, 38, 38)
						.addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(34, 34, 34)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(result)
								.addComponent(airCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
								.addComponent(addButton)
								.addGap(32, 32, 32))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(23, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(airCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(code)
								.addComponent(addButton))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(result)
								.addGap(15, 15, 15))
				);
		setModal(true);
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt,JTextField airCodeField,JLabel result){
		Pattern p=Pattern.compile("[A-Z]{3}");

		Matcher m=p.matcher(airCodeField.getText());
		boolean contained = false;

		//if the string in the field is acceptable when pressed
		if(m.matches())
		{
			//check to make sure the airport doesn't exist in the system
			for(int i=0;i<d.getAirports().size();i++){

				if(d.getAirports().get(i).toString().matches(airCodeField.getText())){
					contained = true;
					break;
					
				}else{

					contained=false;
				}
			}

			if(contained){

				result.setText("Airport already exists in system!");

			}


			else{
				//add the airport to the system
				result.setText("Success!");
				d.addAirport(new Airport(airCodeField.getText(),0,0));
				//show a JDialog box to let them know it was successful
				JOptionPane.showMessageDialog(this,
						("Airport "+d.getAirports().getLast()+" added to the system!"),"Airport added!", JOptionPane.INFORMATION_MESSAGE);
				//reset everything
				result.setText("");
				airCodeField.setText("");

			}

			//history.append("Airport "+d.getAirports().get(d.getAirports().size()-1)+" has been added to the system.\n");
			//System.out.println(d.getAirports().get(d.getAirports().size()-1).toString());

		}else{
			result.setText("Failed! The format is incorrect!");
		}

	}//GEN-LAST:event_addButtonActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JToggleButton addButton;
	private javax.swing.JTextField airCodeField;
	private javax.swing.JLabel code;
	private javax.swing.JLabel result;
	// End of variables declaration//GEN-END:variables
}