import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * This class is used to delete a route from the system. As the user
 * changes the combo box, the fields will auto update, telling the user
 * the information about the route that they currently have selected. When
 * they click the delete button, the program will confirm their selection. 
 */

@SuppressWarnings("serial")
public class DeleteRoute extends javax.swing.JDialog {

	/**
	 * Creates new form DeleteRoute
	 */
	Director d;

	public DeleteRoute(Director d) {
		this.d=d;
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);

		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	//NETBEANS was used to build the GUI to suit our needs. All the actionlisteners were built according to
	//our requirements. 
	private void initComponents() {

		routePanel = new javax.swing.JPanel();
		intructionsLabel = new javax.swing.JLabel();
		routeNumberLabel = new javax.swing.JLabel();
		originLabel = new javax.swing.JLabel();
		destinationLabel = new javax.swing.JLabel();
		departLabel = new javax.swing.JLabel();
		arrivalLabel = new javax.swing.JLabel();
		airlineLabel = new javax.swing.JLabel();
		costLabel = new javax.swing.JLabel();
		deleteButton = new javax.swing.JButton();
		routeBox = new javax.swing.JComboBox();
		originField = new javax.swing.JTextField();
		destField = new javax.swing.JTextField();
		departField = new javax.swing.JTextField();
		arrivalField = new javax.swing.JTextField();
		airlineField = new javax.swing.JTextField();
		costField = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		intructionsLabel.setText("Please Choose the Route to Delete");

		routeNumberLabel.setText("Route #");

		originLabel.setText("Origin");

		destinationLabel.setText("Destination");

		departLabel.setText("Depart Time");

		arrivalLabel.setText("Arrival Time");

		airlineLabel.setText("Airline");

		costLabel.setText("Cost");

		deleteButton.setText("Delete");
		deleteButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteButtonActionPerformed(evt);
			}
		});

		routeBox.setModel(new javax.swing.DefaultComboBoxModel(d.getAllRoutes().toArray()));
		routeBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				routeBoxActionPerformed(evt);
			}
		});

		originField.setEditable(false);

		destField.setEditable(false);
		destField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				destFieldActionPerformed(evt);
			}
		});
		
		airlineField.setText(d.getAllRoutes().getFirst().getAirline());
		arrivalField.setText(Integer.toString(d.getAllRoutes().getFirst().getArrivalTime()));
		costField.setText(Double.toString(d.getAllRoutes().getFirst().getCost()));
		departField.setText(Integer.toString(d.getAllRoutes().getFirst().getDepTime()));
		destField.setText(d.getAllRoutes().getFirst().getDestination().toString());
		originField.setText(d.getAllRoutes().getFirst().getOrigin().toString());

		departField.setEditable(false);

		arrivalField.setEditable(false);

		airlineField.setEditable(false);

		costField.setEditable(false);

		javax.swing.GroupLayout routePanelLayout = new javax.swing.GroupLayout(routePanel);
		routePanel.setLayout(routePanelLayout);
		routePanelLayout.setHorizontalGroup(
				routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, routePanelLayout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addComponent(intructionsLabel)
						.addGap(239, 239, 239))
						.addGroup(routePanelLayout.createSequentialGroup()
								.addGap(45, 45, 45)
								.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(routeNumberLabel)
										.addComponent(routeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(40, 40, 40)
										.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(originLabel)
												.addComponent(originField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(40, 40, 40)
												.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(destinationLabel)
														.addComponent(destField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(40, 40, 40)
														.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(deleteButton)
																.addGroup(routePanelLayout.createSequentialGroup()
																		.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																				.addComponent(departLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																				.addComponent(departField))
																				.addGap(40, 40, 40)
																				.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																						.addComponent(arrivalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(arrivalField))
																						.addGap(40, 40, 40)
																						.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(airlineLabel)
																								.addComponent(airlineField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(40, 40, 40)
																								.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(costLabel)
																										.addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
																										.addContainerGap(46, Short.MAX_VALUE))
				);
		routePanelLayout.setVerticalGroup(
				routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(routePanelLayout.createSequentialGroup()
						.addGap(45, 45, 45)
						.addComponent(intructionsLabel)
						.addGap(18, 18, 18)
						.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(routeNumberLabel)
								.addComponent(originLabel)
								.addComponent(destinationLabel)
								.addComponent(departLabel)
								.addComponent(arrivalLabel)
								.addComponent(airlineLabel)
								.addComponent(costLabel))
								.addGap(18, 18, 18)
								.addGroup(routePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(routeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(originField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(destField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(departField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(arrivalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(airlineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
										.addComponent(deleteButton)
										.addContainerGap())
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(routePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(routePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				);
		setModal(true);
		pack();
	}// </editor-fold>//GEN-END:initComponents

	@SuppressWarnings("unchecked")
	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		
		//make sure the user is sure about what they want
		int result=JOptionPane.showConfirmDialog(this,
				("Are you sure you want to delete "+routeBox.getSelectedItem().toString()+" ?"),"Confirmation", JOptionPane.INFORMATION_MESSAGE);
		if(result==JOptionPane.OK_OPTION){
			//remove and carry on
		d.deleteRoute((Route) routeBox.getSelectedItem());
		JOptionPane.showMessageDialog(this,
				("Route "+routeBox.getSelectedItem().toString()+" has been deleted!"),"Buh bye!", JOptionPane.INFORMATION_MESSAGE);
		if(!d.getAllRoutes().isEmpty()){
		routeBox.setModel(new javax.swing.DefaultComboBoxModel(d.getAllRoutes().toArray()));
		airlineField.setText(d.getAllRoutes().getFirst().getAirline());
		arrivalField.setText(Integer.toString(d.getAllRoutes().getFirst().getArrivalTime()));
		costField.setText(Double.toString(d.getAllRoutes().getFirst().getCost()));
		departField.setText(Integer.toString(d.getAllRoutes().getFirst().getDepTime()));
		destField.setText(d.getAllRoutes().getFirst().getDestination().toString());
		originField.setText(d.getAllRoutes().getFirst().getOrigin().toString());
		d.UpdateInfo();
		}else{
		dispose();	
		}
		}
	}//GEN-LAST:event_deleteButtonActionPerformed

	private void destFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_destFieldActionPerformed

	private void routeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeBoxActionPerformed
		//update the other fields as the combo box is changed
		if(!d.getAllRoutes().isEmpty()){
		int i=routeBox.getSelectedIndex();
		airlineField.setText(d.getAllRoutes().get(i).getAirline());
		arrivalField.setText(Integer.toString(d.getAllRoutes().get(i).getArrivalTime()));
		costField.setText(Double.toString(d.getAllRoutes().get(i).getCost()));
		departField.setText(Integer.toString(d.getAllRoutes().get(i).getDepTime()));
		destField.setText(d.getAllRoutes().get(i).getDestination().toString());
		originField.setText(d.getAllRoutes().get(i).getOrigin().toString());
		}
	}//GEN-LAST:event_routeBoxActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField airlineField;
	private javax.swing.JLabel airlineLabel;
	private javax.swing.JTextField arrivalField;
	private javax.swing.JLabel arrivalLabel;
	private javax.swing.JTextField costField;
	private javax.swing.JLabel costLabel;
	private javax.swing.JButton deleteButton;
	private javax.swing.JTextField departField;
	private javax.swing.JLabel departLabel;
	private javax.swing.JTextField destField;
	private javax.swing.JLabel destinationLabel;
	private javax.swing.JLabel intructionsLabel;
	private javax.swing.JTextField originField;
	private javax.swing.JLabel originLabel;
	private javax.swing.JComboBox routeBox;
	private javax.swing.JLabel routeNumberLabel;
	private javax.swing.JPanel routePanel;
	// End of variables declaration//GEN-END:variables
}
