import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * This class is used to delete an airport from the system. In order 
 * alleviate confusion and silliness, any route associated with that 
 * airport is also deleted. Class takes in a director so that any changes
 * will show to all other classes.
 */

public class deleteAirport extends javax.swing.JDialog {

	Director d;
    /**
     * Creates new form deleteAirport
     */
    public deleteAirport(Director d) {
    	this.d=d;
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    //NETBEANS was used to build a GUI to suit our needs. Any actionlistener was built on a case by case basis
    private void initComponents() {

        stuffPanel = new javax.swing.JPanel();
        promptLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        airportBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Delete Airport");

        promptLabel.setText("Select Airport To Delete");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        airportBox.setModel(new javax.swing.DefaultComboBoxModel(d.getAirports().toArray()));

        javax.swing.GroupLayout stuffPanelLayout = new javax.swing.GroupLayout(stuffPanel);
        stuffPanel.setLayout(stuffPanelLayout);
        stuffPanelLayout.setHorizontalGroup(
            stuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuffPanelLayout.createSequentialGroup()
                .addGroup(stuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stuffPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(promptLabel))
                    .addGroup(stuffPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(stuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airportBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        stuffPanelLayout.setVerticalGroup(
            stuffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuffPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(promptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(airportBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stuffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stuffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        setModal(true);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    //call the delete method within the director
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    	int result=JOptionPane.showConfirmDialog(this,
				("Are you sure you want to delete "+airportBox.getSelectedItem().toString()+" ?"),"Confirmation", JOptionPane.INFORMATION_MESSAGE);
		if(result==JOptionPane.OK_OPTION){
        d.deleteAirport((Airport) airportBox.getSelectedItem());
        airportBox.setModel(new javax.swing.DefaultComboBoxModel(d.getAirports().toArray()));
		}
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox airportBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JPanel stuffPanel;
    // End of variables declaration//GEN-END:variables
}