/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muraad Khan
 */
public class Open_Close_Box extends javax.swing.JFrame {

	//checking for invalid input

	/**
	 * Creates new form Open_Close_Box
	 */
	Director d;

	public Open_Close_Box(Director d) {
		this.d=d;
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Air_Panel2 = new javax.swing.JPanel();
		Combo_Airport2 = new javax.swing.JComboBox();
		From_lbl2 = new javax.swing.JLabel();
		Until_lbl2 = new javax.swing.JLabel();
		Combo_Depart_Time2 = new javax.swing.JTextField();
		Combo_Arrive_Time2 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		Open_Airport_Ok = new javax.swing.JButton();
		Close_tab = new javax.swing.JTabbedPane();
		Air_Panel = new javax.swing.JPanel();
		Combo_Airport = new javax.swing.JComboBox();
		From_lbl = new javax.swing.JLabel();
		Until_lbl = new javax.swing.JLabel();
		Combo_Depart_Time = new javax.swing.JTextField();
		Combo_Arrive_Time = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		Air_Panel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		Until_lbl1 = new javax.swing.JLabel();
		From_lbl1 = new javax.swing.JLabel();
		Combo_Airport1 = new javax.swing.JComboBox();
		Combo_Arrive_Time1 = new javax.swing.JTextField();
		Combo_Depart_Time1 = new javax.swing.JTextField();

		//Air_Panel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Your Airport"));
		setTitle("Open/Close an Airport");

		Combo_Airport2.setModel(new javax.swing.DefaultComboBoxModel(d.getAirports().toArray()));

		From_lbl2.setText("End:");

		Until_lbl2.setText("Begin:");

		jLabel5.setText("Airport:");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		Open_Airport_Ok.setText("OK");

		Air_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Opening an Airport"));

		Combo_Airport.setModel(new javax.swing.DefaultComboBoxModel(d.getAirports().toArray()));

		From_lbl.setText("End:");

		Until_lbl.setText("Begin:");

		jLabel3.setText("Airport:");

		javax.swing.GroupLayout Air_PanelLayout = new javax.swing.GroupLayout(Air_Panel);
		Air_Panel.setLayout(Air_PanelLayout);
		Air_PanelLayout.setHorizontalGroup(
				Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(Air_PanelLayout.createSequentialGroup()
						.addGap(67, 67, 67)
						.addGroup(Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(Until_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(From_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
								.addGap(30, 30, 30)
								.addGroup(Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(Combo_Airport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(Combo_Depart_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Combo_Arrive_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addContainerGap(145, Short.MAX_VALUE))
				);
		Air_PanelLayout.setVerticalGroup(
				Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(Air_PanelLayout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addGroup(Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Combo_Airport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
								.addGap(18, 18, 18)
								.addGroup(Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(Combo_Depart_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(Until_lbl))
										.addGap(18, 18, 18)
										.addGroup(Air_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Combo_Arrive_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(From_lbl))
												.addContainerGap(46, Short.MAX_VALUE))
				);

		Close_tab.addTab("Open", Air_Panel);

		Air_Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Closing an Airport"));

		jLabel4.setText("Airport:");

		Until_lbl1.setText("Begin:");

		From_lbl1.setText("End:");

		Combo_Airport1.setModel(new javax.swing.DefaultComboBoxModel(d.getAirports().toArray()));

		javax.swing.GroupLayout Air_Panel1Layout = new javax.swing.GroupLayout(Air_Panel1);
		Air_Panel1.setLayout(Air_Panel1Layout);
		Air_Panel1Layout.setHorizontalGroup(
				Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(Air_Panel1Layout.createSequentialGroup()
						.addGap(67, 67, 67)
						.addGroup(Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(Until_lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(From_lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
								.addGap(30, 30, 30)
								.addGroup(Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(Combo_Airport1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(Combo_Depart_Time1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Combo_Arrive_Time1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addContainerGap(145, Short.MAX_VALUE))
				);
		Air_Panel1Layout.setVerticalGroup(
				Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(Air_Panel1Layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addGroup(Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Combo_Airport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
								.addGap(18, 18, 18)
								.addGroup(Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(Combo_Depart_Time1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(Until_lbl1))
										.addGap(18, 18, 18)
										.addGroup(Air_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Combo_Arrive_Time1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(From_lbl1))
												.addContainerGap(46, Short.MAX_VALUE))
				);

		Close_tab.addTab("Close", Air_Panel1);
		Air_Panel1.getAccessibleContext().setAccessibleName("Close an airport");
		Air_Panel1.getAccessibleContext().setAccessibleDescription("");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(Close_tab)
				.addGroup(layout.createSequentialGroup()
						.addGap(141, 141, 141)
						.addComponent(Open_Airport_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(Close_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(Open_Airport_Ok)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		Close_tab.getAccessibleContext().setAccessibleName("Open an airport");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel Air_Panel;
	private javax.swing.JPanel Air_Panel1;
	private javax.swing.JPanel Air_Panel2;
	private javax.swing.JTabbedPane Close_tab;
	private javax.swing.JComboBox Combo_Airport;
	private javax.swing.JComboBox Combo_Airport1;
	private javax.swing.JComboBox Combo_Airport2;
	private javax.swing.JTextField Combo_Arrive_Time;
	private javax.swing.JTextField Combo_Arrive_Time1;
	private javax.swing.JTextField Combo_Arrive_Time2;
	private javax.swing.JTextField Combo_Depart_Time;
	private javax.swing.JTextField Combo_Depart_Time1;
	private javax.swing.JTextField Combo_Depart_Time2;
	private javax.swing.JLabel From_lbl;
	private javax.swing.JLabel From_lbl1;
	private javax.swing.JLabel From_lbl2;
	private javax.swing.JButton Open_Airport_Ok;
	private javax.swing.JLabel Until_lbl;
	private javax.swing.JLabel Until_lbl1;
	private javax.swing.JLabel Until_lbl2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables
}
