import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brian
 */
public class addAirport extends javax.swing.JFrame {

	/**
	 * Creates new form addAirport
	 */
	Director d;
	
	 JTextArea history;// added
	 
	public addAirport(Director d,JTextArea history) {
		this.d=d;
		initComponents();
		setLocationRelativeTo(null);
		setVisible(true);
		this.history = history;// added
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		code = new javax.swing.JLabel();
		airCodeField = new javax.swing.JTextField();
		addButton = new javax.swing.JToggleButton();
		result = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Add a New Airport");

		code.setText("Airport Code");

		addButton.setText("Add");
		addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	addAirportOptionActionPerformed(evt);
            }
        });//change
        

		result.setText("                                 ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(38, 38, 38)
						.addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(34, 34, 34)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(result)
								.addComponent(airCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
								.addComponent(addButton)
								.addGap(32, 32, 32))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(23, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(airCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(code)
								.addComponent(addButton))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(result)
								.addGap(15, 15, 15))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents
	 private void addAirportOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRouteOptionActionPerformed
			history.append("A new airport has been added to the system.\n");
		}//added
	private void addButtonActionPerformed(java.awt.event.ActionEvent evt,JTextField airCodeField,JLabel result){
		Pattern p=Pattern.compile("[A-Z]{3}");

		Matcher m=p.matcher(airCodeField.getText());

		if(m.matches())
		{

			result.setText("Success!");
			d.addAirport(new Airport(airCodeField.getText(),0,0));
			//System.out.println(d.getAirports().get(d.getAirports().size()-1).toString());

		}else{
			result.setText("Failed! The format is incorrect!");
		}

	}//GEN-LAST:event_addButtonActionPerformed

	/*
public void passDirector(Director d){

    	this.d = (Director)d.clone();

    }
public Director updateDirector(){

	return d;
}
	 */
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JToggleButton addButton;
	private javax.swing.JTextField airCodeField;
	private javax.swing.JLabel code;
	private javax.swing.JLabel result;
	// End of variables declaration//GEN-END:variables
}
